version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: portfolio_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/Data:/docker-entrypoint-initdb.d  # optional: auto-run init SQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: .
    container_name: bond_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db         # 👈 match service name
      DB_ROOT_USER: root
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - .:/app  # optional: live code reload for dev
      - ./logs:/app/logs  # persist logs for admin log viewer
    command: >
      sh -c "python wait-for-db.py db 3306 && 
             python setup.py && 
             gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
